Repository Samyak2/toipe, pull requests merged in 2022-04, with the labels that each got.

#5 Support more words
  README.md
  src/config.rs
  src/lib.rs
  src/tui.rs
Labels: enhancement

#7 Better README
  README.md
  images/toipe.gif
Labels: documentation

#20 More shortcuts
  Cargo.toml
  README.md
  src/config.rs
  src/lib.rs
  src/tui.rs
Labels: enhancement

#22 Fix wpm
  src/lib.rs
  src/results.rs
Labels: bug, enhancement

#28 fix: print error message when terminal size is less the number of lines
  src/lib.rs
  src/main.rs
  src/tui.rs
Labels: enhancement
